USE roomAllocaor;

INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Superacion','0','10');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Dialogo','0','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Futuro','0','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Crecimiento','0','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Desarrollo','0','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Eficiencia','1','8');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Calidad','1','8');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Mejora','1','4');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Rendimiento','1','4');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Comunicación','-1','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Valor','-1','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Optimismo','-1','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Estrategia','-1','10');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Ilusión','-1','3');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-2B-01','2','6');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-2B-02','2','6');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-2B-03','2','4');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-2B-04','2','4');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-2B-05','2','6');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-2B-06','2','4');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Transformar','2','10');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Imaginar','2','4');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Actitud','2','16');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Conocimiento','2','8');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Motivación','2','8');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Multiusos','2','40');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Phone Booth 2B-01','2','2');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Phone Booth 2B-01','2','2');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Productividad','2','8');
INSERT INTO RoomInformations(Name,Floor,NumRoom)VALUES('SVQ-Cartuja-Solidaridad','2','8');