// <auto-generated />
using System;
using APISalasEveris.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APISalasEveris.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20190411094822_Rooms-Buildings-Offices")]
    partial class RoomsBuildingsOffices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APISalasEveris.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuildingName");

                    b.Property<int>("NumberOfStreet");

                    b.Property<int>("OfficeId");

                    b.Property<string>("Street");

                    b.Property<int?>("idOffice");

                    b.HasKey("BuildingId");

                    b.HasIndex("idOffice");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("APISalasEveris.Models.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias");

                    b.Property<string>("OfficeName");

                    b.HasKey("OfficeId");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("APISalasEveris.Models.RoomInformation", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingId");

                    b.Property<int>("Floor");

                    b.Property<string>("NumRoom");

                    b.Property<string>("RoomName");

                    b.Property<int?>("idBuilding");

                    b.HasKey("RoomId");

                    b.HasIndex("idBuilding");

                    b.ToTable("RoomInformations");
                });

            modelBuilder.Entity("APISalasEveris.Models.Building", b =>
                {
                    b.HasOne("APISalasEveris.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("idOffice");
                });

            modelBuilder.Entity("APISalasEveris.Models.RoomInformation", b =>
                {
                    b.HasOne("APISalasEveris.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("idBuilding");
                });
#pragma warning restore 612, 618
        }
    }
}
